# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-23 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joins', '0007_auto_20170223_1023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='ip_address',
        ),
    ]
